name: stable

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
        ruby: [ 2.5.8, 2.6.6, 2.7.1, jruby-9.2.12.0 ]
        include:
          - { os: ubuntu-20.04, ruby: 2.7.1 }
    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: latest

      - name: Get sqlite for Rails test projects
        run: sudo apt-get install libsqlite3-dev

      - name: Install dependencies
        run: |
          ruby -e 'puts RUBY_DESCRIPTION'
          bundle config set --local without benchmark
          bundle install --jobs=3

      - name: Run tests (MRI)
        run: bundle exec rake
        if: "!startsWith(matrix.ruby, 'jruby')"

      - name: Run tests (JRuby)
        run: JRUBY_OPTS=--debug bundle exec rake
        if: startsWith(matrix.ruby, 'jruby')
