name: unstable

#on:
#  schedule:
#    - cron: '0 0 * * *'

on: [push, pull_request]

jobs:
  test:
    # if: github.repository == 'simplecov-ruby/simplecov'
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ head, jruby-head ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: latest

      - name: Get sqlite for Rails test projects
        run: sudo apt-get install libsqlite3-dev

      - name: Install dependencies
        run: |
          bundle config set --local without benchmark
          bundle lock --update
          bundle install --jobs=3

      - name: Run tests (MRI)
        run: bundle exec rake
        if: "!startsWith(matrix.ruby, 'jruby')"

      - name: Run tests (JRuby)
        run: JRUBY_OPTS=--debug bundle exec rake
        if: startsWith(matrix.ruby, 'jruby')
